### ISSUE TITLE
Update various non-code files in this repo

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#1695]
- [x] lib-src/audacity-patches.txt references svn, cvs and googlecode extensively #845
- [x] todo.txt can be removed, it's last modified 9 years ago  #1671
- [x] CONTRIBUTING.md is outdated and should link to current resources instead #1670
- [x] CHANGELOG.txt got last updated with 3.0.0. We should either keep it up-to-date (#593) or add a notice saying "this isn't updated anymore, check the release notes/what's new section in the wiki/manual"
- [x] README.txt got last updated with 3.0.3, but it still mostly reports 3.0.2 contents. It also features a changelog in it, so it kinda is redundant to the CHANGELOG.txt?
- [x]  #1983
- [ ] https://github.com/audacity/audacity/blob/master/help/audacity.appdata.xml is very out of date

**Comment by SteveDaulton** [comment]
+1 for an up to date changelog.
Lots of reasons why this is an important document.

**Comment by LWinterberg** [comment]
the last remaining issue resurfaced as #4780, this one is done
