### ISSUE TITLE
Logo refresh considerations

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#1784]
- [ ] There need to be several versions of the outside shape of icons to conform with OS standards, ie square/circle/squircle ones (see also #1782)
- [ ] The favicons among the wiki/website/manual/forum should be unified into one
- [ ] AUP/AUP3 projects should get their own icons (see also #480 )
- [ ] there probably should be variants for dark/light/colored backgrounds
- [ ] There currently is some extensive stretching of the text occuring to wrestle the logo+wordmark into square spacing, this should be done more elegantly (see also #1392)

Note to contributors: there already are [copious amounts of logo proposals from the community](https://forum.audacityteam.org/viewtopic.php?f=67&t=83108). We aren't really looking into a full redesign, but rather of a refresh of the current logo to slightly modernize it, clean it up, and dejankify it. Make sure to check in with [the dev discord](https://discord.gg/Hj2Gh7DMcB) before spending lots of time on a thing we may not need or want :)

**Comment by LWinterberg** [comment]
Github really isn't the right place for logo talk :)
