### ISSUE TITLE
Checklist: VST2, LV2, AudioUnits effects don't monitor output

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2553]
**Describe the bug**
- [x] VST2 effects should monitor output
- [x] VST3 effects should monitor output
- [x] LV2 effects should monitor output
- [x] #3069

**To Reproduce**
1. Enable a realtime effect with some kind of graphical display of output, for instance AUDynamicsProcessor on Mac, which has an output meter (but this should be tested and confirmed for each effect family)
2. Generate some noise
3. Open the effect
4. Press the Play button
5. Vary input parameters during play (drag points on the curve in this example)
6. Observe:  the sound does change with variation of parameters, but there is no graphical output

**Additional information (please complete the following information):**
 - OS: all
 - Version 3.2.0 only: regression on 3.1.3, which began at commit 81951ab

**Additional context**
- I repeat: a fix should be tested for each of the three effect families named above; also verified with VST3 when support for that is merged

**Comment by Penikov** [comment]
Confirm. Now, these types of plugins have no graphical input, in Master brach.

**Comment by Penikov** [comment]
UPD:

Have finished regression checks for supported types of plug-ins.

Basically, in 3.2 we have similar problems on different plug-in types which are supported by Audacity.

Unfortunately, there are not only UI issues like output visualization but also 
large latency on effect preview.
In particular, VST plug-in Kotelnikov works well in 3.1.3, but _has huge latencies on preview_ and missed output indication in 3.2.

The same issues with AU. AUDinamicsProcessor from Garage Band distribution works fine in 3.1.3 but has a broken output indication.

In LV2 Renegate plug-in (https://www.auburnsounds.com/products/Renegate.html) preview playback does not work properly (in comparison with 3.1.3 )
