### ISSUE TITLE
Beats & Measures implementation

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#4150]
Figma: https://www.figma.com/file/SKDJypvy37EAauTPgwo2tL/07_WX---Beats-%26-measures?node-id=30%3A761&t=akJxcFIv1Xix5oAc-0

 ## Primarily @micpap25 

- [x] Timeline (right-click to set it to beats and measures) - see https://github.com/audacity/audacity/pull/4394
- [x] https://github.com/audacity/audacity/issues/4421 (partly fixed by #4437)
- [x] #4412 (partly fixed by #4437)
- [x] https://github.com/audacity/audacity/issues/4423 (partly fixed by #4473)
- [ ] Bug fix for https://github.com/audacity/audacity/issues/4411 (partly preexisting asymmetries)
- [ ] #4439 (reported by Michael, partly addressed in #4437)
- [ ] #4440 (reported by Peter)

## Primarily team

- [x] Group snapping options
- [x] Tempo & time signature toolbar
- [x]  Move project rate to audio setup
- [x] Group selection toolbar time options  
    (optional)
- [x] https://github.com/audacity/audacity/issues/4283
- [x] https://github.com/audacity/audacity/issues/4285
- [x] https://github.com/audacity/audacity/issues/4284
- [x] https://github.com/audacity/audacity/issues/4457
- [ ] https://github.com/audacity/audacity/issues/4455
- [x] https://github.com/audacity/audacity/issues/4456
- [x] https://github.com/audacity/audacity/issues/4461
- [x] https://github.com/audacity/audacity/issues/4474
- [ ] https://github.com/audacity/audacity/issues/4486

## design

- [x] spec interactions: clip moving, trimming
- [x] spec selection toolbar tied to snapping

**Comment by micpap25** [comment]
I am working at https://github.com/micpap25/audacity/tree/post-gsoc-3
I just pushed changes that should address #4421 and part of #4412
I will work on the rest of #4412 and all of #4423 tomorrow

**Comment by LWinterberg** [comment]
This tracking bug is no longer necessary, the remaining issues can continue existing as stray ones
