### ISSUE TITLE
Restructuring for wide stereo clips (checklist)

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4681]
- [x] Library reorganizations to support stretching
  - [x] #4754 (Remove lib-effects -> lib-audio-io)
  - [x] #4759 (Remove lib-audio-graph->lib-track)
  - [x] #4746 (Add lib-mixer, not using lib-track)
  - [x] #4795 (Remove lib-audio-graph->lib-track)
  - [x] #5130 (This PR is also in the next section)
- [x] De-duplication of WaveTrack data
   - [x] #2804
   - [x] #4737
   - [x] #5027
   - [x] #5101
   - [x] #5116
   - [x] #5121
   - [x] #5127 
   - [x] #5130
- [x] Rewrite outer loops over tracks (introducing new inner loops over channels); visit leaders only
  - [x] #4738
  - [x] #4886
  - [x] #4908
  - [x] #4937
  - [x] #4945
  - [x] #4961
  - [x] #4974
- [x] Rewrite inner loops over channels (remove `TrackList::Channels` outside `Track` and` WaveTrack`; hide STL track iterators)
  - [x] #4825
  - [x] #4844
  - [x] #4987
  - [x] #5008
  - [x] #5031
  - [x] #5131
  - [x] #5128
  - [x] #5091 
  - [x] #5159
  - [x] #5212
  - [x] #5180 (Includes "Wide" RecordableSequences)
  - [x] #5530
- [x] Change channel-major iterations to interval-major (except in effects, display, recording)
  - [x] #4876
  - [x] #5065 
  - [x] #5198
- [x] Re-implement representation of channels
   - [x] #6086
   - [x] #4742
   - [x] #5156
   - [x] #6081
   - [x] #4954
   - [x] #6070
   - [x] #6072
   - [x] #5460
- [x] Implement joining of channels according to design
   - [x] #5200
- [x] File compatibility break
   - [x] #5201
   - [x] #5202
   - [x] #5211
- Incidental fixes
  - #4725
  - #4730
  - #4714 
  - #4718
  - #4713 
  - #4716

**Comment by Paul-Licameli** [comment]
Force-pushed once more with one commit inserted first in the sequence to fix crashes in sync-lock

**Comment by Paul-Licameli** [comment]
The fourth and fifth main headings of the outline are checked off after #5965 is merged
