### ISSUE TITLE
Clip stretching control through clip menu

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5192]
Purpose of this ticket is to list tasks needed to getting this [design from Leo](https://www.figma.com/file/3vAMBYovsJuTrbet34ruaZ/08_WX---Clips?type=design&node-id=1104-27663&mode=design&t=2hrkDl0qPr6A3b2s-0) complete.
Check boxes below may be implemented individually, grouped together or some may be discarded or postponed to some other milestone.

### Tasks

- [x] [Right-click on clip header selects it all and shows the clip menu ](https://github.com/audacity/audacity/issues/5195)
- [x] [Speed dialog: interactive clip speed textbox](https://github.com/audacity/audacity/issues/5196)
- [x] #5238
- [ ] Speed dialog: "Adjust clip when changing project tempo" - this must be remembered when saving projects ; What happens when unstretchable clips start colliding with others ?

**Comment by DavidBailes** [comment]
> Purpose of this ticket is to list tasks needed to getting this [design from Leo](https://www.figma.com/file/3vAMBYovsJuTrbet34ruaZ/08_WX---Clips?type=design&node-id=1104-27663&mode=design&t=2hrkDl0qPr6A3b2s-0) complete.

@LWinterberg . Please could you give me access to the figma for this?

**Comment by Paul-Licameli** [comment]
> Hey @saintmatthieu, as you requested, I've ticked the things that should be in 3.4
> 
>     * [x]  Right-click on clip header selects it all and shows the clip menu
> 
>     * [ ]   Speed dialog: "Apply destructively" button - should be easy
> 
>     * [ ]   Speed dialog: interactive clip speed textbox - mind possible collision with other clips when expanding. I suppose this should stretch clip by the right edge ?
> 
>     * [x]   Speed dialog: "Adjust clip when changing project tempo" - this must be remembered when saving projects ; What happens when unstretchable clips start colliding with others ?
> 
>     * [x]  A text box that allows you to manually edit the % speed

Observe that double clicking on pan or gain sliders now makes a dialog too.

Maybe some of that dialog code could be adapted and reused, or maybe not.

**Comment by saintmatthieu** [comment]
@Tantacrul thanks for your input. I have now linked cards to some of the checkboxes, and those have the 3.4 milestone.

**Comment by DavidBailes** [comment]
> > Purpose of this ticket is to list tasks needed to getting this [design from Leo](https://www.figma.com/file/3vAMBYovsJuTrbet34ruaZ/08_WX---Clips?type=design&node-id=1104-27663&mode=design&t=2hrkDl0qPr6A3b2s-0) complete.
> 
> @LWinterberg . Please could you give me access to the figma for this?

@LWinterberg . Please could you either give me access to this or let me know how the Speed dialog for a selected clip is going to be keyboard accessible in 3.4.

**Comment by LWinterberg** [comment]
ah, sorry @DavidBailes I missed your earlier comments! Please either DM me your email you use in figma, or press the "request access" button when you load up the page so I can add you

**Comment by DavidBailes** [comment]
@LWinterberg . Thanks, I've now got access to the figma. However, I couldn't find any info on making the Clip speed dialog accessible for keyboards users.
One straightforward way of doing this would be to add a "Change speed..." command to the Audio clips sub menu of the Edit menu. This command could work in a similar way to the Rename clip... command on the Edit menu.
Can something like this be please included in 3.4, so that the main new feature in that release is also accessible for keyboard users?

**Comment by DavidBailes** [comment]
> > One straightforward way of doing this would be to add a "Change speed..." command to the Audio clips sub menu
> 
> It will be there for sure :-)

That's great!

**Comment by saintmatthieu** [comment]
This ticket is complete except for the "Adjust clip when changing project tempo" toggle, which wasn't made part of 3.4.
This topic will come back again, either as user requests, or when we tackle automatic detection of clip tempi. For now cleaning-up the backlog by closing this bigger checklist issue.
