### ISSUE TITLE
Experimental features todo list

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#6222]
Audacity currently has various functions build-in but disabled in typical builds. Ideally, the number of functions carried around in this manner is 0 in the long term. This task list is to help with that.

### Discussed in https://github.com/audacity/audacity/discussions/6210

<div type='discussions-op-text'>

<sup>Originally posted by **LWinterberg** April  3, 2024</sup>

- [x] Remove CEE_NUMBERS_OPTION
    - [ ] Implement a locale setting for number formats instead
- [x] Remove SPECTROGRAM_OVERLAY 
- [x] Refactor tracks such that selection becomes an overlay on top of waveform/spectrogram/notes
- [x] Move THEME_PREFS into a module
     - [ ] Move the THEME_PREFS functionality into a non-modal window (for faster trying out)
     - [x] AU4: Remove
- [x] Remove ROLL_UP_DIALOG
- [x] Remove ExpandingToolBar
- [x] Remove RIGHT_ALIGED_TEXBOXES
- [x] Remove VOICE_DETECTION
- [x] Remove FIND_NOTES
- [x] Remove FFT_Y_GRID
- [x] Remove SEEK_BEHIND_CURSOR
- [x] remove IMPROVED_SEEKING
- [x] Remove METER_LED_STYLE
- [x] Remove TRACK_PANEL_HIGHLIGHTING
- [x] Remove DRAG_DROP_PLUG_INS  
   Plugins are not guaranteed to be fully self-contained - and generally want to be available system-wide.
- [x] Remove EASY_CHANGE_KEY_BINDINGS
- [x] Remove AUTOMATED_INPUT_LEVEL_ADJUSTMENT

### still to be decided

these may be good candidates for inclusion but likely need more investigation on their merits, and additional work 

* BRUSH_TOOL
* MIDI_IN
* MIDI_STRETCHING
* SCOREALIGN
* DEVICE_CHANGE_HANDLER
</div>
